name: Builder Humble amd64

on:
  workflow_dispatch:
  push:
    paths:
      - ros2.repos
jobs:
  build_testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: qiayuanl/livox_ros_driver2
          token: ${{ secrets.GH_PAT }}
          path: 'src/livox_ros_driver2'
      - uses: qiayuanl/ros-deb-builder-action@main
        with:
          DEB_DISTRO: jammy
          ROS_DISTRO: humble
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
          SKIP_CHECKOUT: true
    
